
package webserviceimm;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WebserviceTicketsIMMService", targetNamespace = "http://webserviceIMM/", wsdlLocation = "http://localhost:8080/TallerPrevioJEE5_SistemaIMM/WebserviceTicketsIMM?wsdl")
public class WebserviceTicketsIMMService
    extends Service
{

    private final static URL WEBSERVICETICKETSIMMSERVICE_WSDL_LOCATION;
    private final static WebServiceException WEBSERVICETICKETSIMMSERVICE_EXCEPTION;
    private final static QName WEBSERVICETICKETSIMMSERVICE_QNAME = new QName("http://webserviceIMM/", "WebserviceTicketsIMMService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/TallerPrevioJEE5_SistemaIMM/WebserviceTicketsIMM?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WEBSERVICETICKETSIMMSERVICE_WSDL_LOCATION = url;
        WEBSERVICETICKETSIMMSERVICE_EXCEPTION = e;
    }

    public WebserviceTicketsIMMService() {
        super(__getWsdlLocation(), WEBSERVICETICKETSIMMSERVICE_QNAME);
    }

    public WebserviceTicketsIMMService(WebServiceFeature... features) {
        super(__getWsdlLocation(), WEBSERVICETICKETSIMMSERVICE_QNAME, features);
    }

    public WebserviceTicketsIMMService(URL wsdlLocation) {
        super(wsdlLocation, WEBSERVICETICKETSIMMSERVICE_QNAME);
    }

    public WebserviceTicketsIMMService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WEBSERVICETICKETSIMMSERVICE_QNAME, features);
    }

    public WebserviceTicketsIMMService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WebserviceTicketsIMMService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WebserviceTicketsIMM
     */
    @WebEndpoint(name = "WebserviceTicketsIMMPort")
    public WebserviceTicketsIMM getWebserviceTicketsIMMPort() {
        return super.getPort(new QName("http://webserviceIMM/", "WebserviceTicketsIMMPort"), WebserviceTicketsIMM.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WebserviceTicketsIMM
     */
    @WebEndpoint(name = "WebserviceTicketsIMMPort")
    public WebserviceTicketsIMM getWebserviceTicketsIMMPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webserviceIMM/", "WebserviceTicketsIMMPort"), WebserviceTicketsIMM.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WEBSERVICETICKETSIMMSERVICE_EXCEPTION!= null) {
            throw WEBSERVICETICKETSIMMSERVICE_EXCEPTION;
        }
        return WEBSERVICETICKETSIMMSERVICE_WSDL_LOCATION;
    }

}
